### ISSUE TITLE
Is the javascript executed on the remote server or on the client browser?

### ISSUE THREAD

**Issue by anton-thushara** [intoli/remote-browser#78]
When you connect remotely to a server. Is the javascript execution done on the remote server or on the client browser? i guess what i'm trying to figure out is that when you connect to a remote server does the browser becomes just a DOM viewer and all of the JS executions happens on a remote server.  i'm in need of a library to create a cloud browser such as puffin. i need to offload all of JS executions to a remote server.

**Comment by ROBERT-MCDOWELL** [comment]
I have the same question but want to secure some Flash application with
a remote browser as a client terminal connecting to a browser on the server.

**Comment by sangaline** [comment]
The client/server terminology might be a little confusing here because, in a technical sense, both the browser and the controller code are clients connecting to an intermediating server. One of those clients runs in an actual web browser, and the other runs in the code that is used to control the browser. I would colloquially think of the latter as the client because it issues requests to the browser and gets responses from it.

Any of the code that you run from the remote client will be executed in the browser. For example, if you run `browser.tabs.captureVisibleTab()` from a client running in node, then it will proxy that request to the browser it's connected to, execute the command in that browser, and then returns the response to the client. There is no browser emulation anywhere, it's only a way to control a browser like you can do with Selenium or Puppeteer.

I hope that clears things up, let me know if you still have questions.
